dist: xenial
language: python
matrix:
  include:
    - python: "2.7"
    - python: "3.7"
before_install:
  - sudo apt-get install -y git
  # Doesn't work for some reason, so we'll just skip tests that invoke git
  # commands requiring these options to be configured on Travis
  # - git config --global user.email "foo@bar.com"
  # - git config --global user.name "Foo Bar"
install: pip install tox-travis
script: tox -- -m "not git"
